import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour2Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 2",
      "Pour le deuxième jour, vous avez le droit de prendre du café sans sucre (sauf sucre de synthèse), avec un peu de lait (environ 20% de votre tasse de 20cl).\nComme d'habitude, il est recommandé de choisir du café vert plutôt que des cafés riches en calories comme le cappuccino (qui contient 70 kcalories par tasse de café, sans sucres ajoutés). Le café vert a la particularité d'augmenter le rythme cardiaque, ce qui facilitera votre perte de poids car vous consommerez davantage de calories.",
      "Au déjeuner, vous avez le droit de manger un grand steak, ainsi qu'une salade et des fruits à volonté.\nPourquoi un grand steak ? Afin de conserver votre masse musculaire, il est important de consommer des protéines. L'apport journalier recommandé en matière de protéines pour le corps humain est d'en moyenne 0,8 grammes multiplié par votre poids en kilos (si vous pesez par exemple 70 kilos, votre apport journalier recommandé en protéines est de 56 grammes) La viande, et notamment la viande bovine, est un excellent apport de protéines. Un steak de bœuf contient 28 grammes de protéines pour 100 grammes, ce qui l'en fait l'un des aliments les plus riches en protéines. En consommant votre steak, vous satisferez les besoins de votre corps en matière de masse musculaire. En d'autres termes, vous ne perdrez pas de muscles. C'est pour cette raison qu'il est important (et même vital) de consommer votre steak.\nPour la salade, n'importe quelle salade fera l'affaire à condition de l'assaisonner sans huile végétale (pas d'huile d'olives,...), mais avec du jus de citron fait maison (pressez un ou deux citron suivant le volume de salade désiré).\nPour les fruits à volonté, il est préférable d'éviter tous les fruits avec un apport calorique élevé, mais plutôt privilégier les fruits comme le kiwi (47 kcalories pour 100 grammes), la pomme (50 kcalories pour 100 grammes), la poire (61 kcalories pour 100 grammes). Chacun de ces produits a l'avantage d'être très riche en vitamines (vitamine C,...). La pomme reste le fruit idéal, car non seulement elle ne contient quasiment aucune calorie, mais elle présente également le gros avantage d'agir comme un coupe-faim.",
      "Pour le dîner, vous pouvez manger du jambon cuit à volonté sans aucune restriction.\nPourquoi du jambon cuit ? Le jambon est un aliment hyperprotéiné, ce qui en fait un aliment parfait pour le régime Thonon. Avec une tranche de jambon de 50 grammes, vous pouvez notamment couvrir en moyenne 13% des besoins journaliers recommandés en protéines pour les hommes et environ 17% des apports journaliers recommandés en protéines pour les femmes (les apports journaliers recommandés en protéines dépendent principalement de votre poids : en moyenne 0,8 grammes de protéine multiplié par votre poids en kilos). Le jambon cuit a également la particularité d'être très pauvre en calories : en moyenne, 50 grammes de jambon cuit ne contient qu'à peine 60 calories, ce qui en fait un aliment à très faible apport calorique. Un autre avantage de taille : il ne contient que très peu de matières grasses (environ 3 grammes pour 100 grammes de jambon cuit).",
    );
  }
}
