import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour14Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 14",
      "Pour le petit-déjeuner, vous avez le choix entre trois boissons chaudes. Du café vert, du thé vert ou bien une tisane au citron.\nLe café et le thé vert sont des boissons qui sont particulièrement recommandées lors de régimes amaigrissants, et trouvent très bien leur place dans le régime Thonon.\nPour le café, il faut le choisir de préférence vert, car il garde toutes ses vertus car il n’est pas torréfié, ce qui lui confère toutes ses propriétés naturelles. Le café vert est réputé pour aider à perdre du poids et est également très bon pour la santé. Il abaisserait le taux de diabète chez les personnes atteintes de diabète 2, c’est-à-dire celles qui ont un poids trop important.\nQuant au thé vert, il a également les propriétés d’être une boisson qui fait perdre du poids par ses principes actifs et également de faire baisser la tension.\nLa tisane au citron est une boisson détoxifiante. Prise le matin au petit-déjeuner, elle a une action détox sur votre foie, et permet d’éliminer les graisses également. Elle est également très appréciée pour le transit intestinal. Le citron a de nombreuses vertus. C’est un diurétique, il facilite l’élimination des toxines, il prépare à digérer les aliments à venir. Il limite également le taux de glycémie, ce qui permet de stabiliser le taux de sucre dans le sang, et cette stabilité entraîne une perte de poids.",
      "Pour le déjeuner de votre dernière journée du régime Thonon, vous avez le droit de manger un grand steak et des fruits à volonté.\nPetit rappel : il ne faut pas saler votre viande et la faire griller sans matières grasses. Vous pouvez la faire revenir dans une poêle ou la faire griller à l’aide d’un grille viande.\nLa viande bovine est importante dans un régime. Elle est source de protéines, et l’organisme à besoin de protéines pour protéger la masse musculaire. Vous ne devez pas faire l’impasse sur le steak, au risque de déséquilibrer les menus élaborés pour le régime Thonon.\nVous pouvez saupoudrez votre viande grillée de quelques herbes aromatiques pour lui donner une saveur particulière.\nPas de légumes, ni de salade mais des fruits à volonté. Vous pouvez donc reprendre la liste des fruits autorisés à volonté dans la rubrique « les fruits à volonté, comment les choisir ? ».\nComme vous n’avez eu le droit qu’à un steak au déjeuner, vous risquez de rester un peu sur votre faim. Pour cela, vous pouvez très bien manger deux bananes, deux ou trois fruits secs pour calmer la sensation de faim et terminer par des fruits moins caloriques, comme la poire, les cerises selon la saison, le melon, l’ananas, le kiwi qui est très riche en vitamine C, des mandarines. A vous de voir vos préférences concernant les fruits.\nVous pouvez terminer ce repas par une pomme. Ce fruit est très pauvre en calories, et est un excellent coupe-faim, de quoi tenir jusqu’au prochain repas, le dîner !",
      "Votre dernière soirée de régime Thonon vous donne droit à tout ce que vous souhaitez manger.\nToutefois, nous vous conseillons de manger dans des proportions raisonnables, car votre estomac n’est plus aussi accueillant pour recevoir d’un seul coup, une quantité importante d’aliments.\nLes seules restrictions sont le fait de ne pas manger de sucreries, et surtout de ne pas boire d’alcool.\nPour le reste, vous avez « carte blanche », faites-vous plaisir tout en restant dans le raisonnable.\nLe régime Thonon est terminé pour cette période de 14 jours, mais maintenant il va falloir stabiliser votre poids. Donc, si vous êtes toujours motivée, vous garderez de ces 14 jours, la manière de mieux vous alimenter.\nVous avez pris de bonnes habitudes, découvert une nouvelle manière de manger, alors gardez-en le bénéfice !",
    );
  }
}
