import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour10Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 10",
      "Vous avez le droit de boire du café vert ou bien du thé vert sans sucre. Le sucre de synthèse est autorisé, si vous ne pouvez pas boire votre boisson chaude non sucrée.\nAvec votre thé ou café, vous pouvez manger un petit pain ou une belle tranche de pain aux céréales. Il est conseillé de manger du pain complet. En effet, le pain complet est plus riche en fibres et en nutriments que le pain blanc. Il vous assurera un bon transit intestinal. De plus, il vous évitera le petit creux de 11 heures, car le plain complet se digère plus lentement que le pain blanc. Il vous évitera, ainsi, des fringales en milieu de matinée. C’est pour cela qu’il est conseillé au petit-déjeuner dans le régime Thonon.",
      "Pour le déjeuner du dixième jour, vous avez le droit de manger deux œufs durs et en accompagnement de la salade verte et des tomates à volonté. Le sel est interdit.\nPourquoi des œufs durs ?\nLes œufs durs sont couramment utilisés dans les régimes comme le régime Thonon, car ce sont des coupe-faim exceptionnels. De plus, les œufs durs sont riches en protéines et faibles en calories. Ce qui en fait un élément parfait pour perdre du poids. Il peut également très bien se substituer à la viande car il est quasiment aussi riche en protéines que celle-ci. Bien entendu, lors du régime Thonon, il faut suivre à la lettre le régime et ne pas changer les aliments, ni l’ordre de ceux-ci.\nLes œufs sont également riches en vitamines. On trouve de la vitamine A, D, E et B12 ainsi que du magnésium, du phosphore, du zinc et du potassium.\nVous accompagnerez vos œufs durs avec de la salade verte à volonté. Vous pouvez varier entre les différentes salades comme la frisée, la laitue, la roquette ou encore la scarole, et des tomates également à volonté, toujours en oubliant le sel.\nPour changer un peu votre menu, vous pouvez fort bien vous préparer une petite salade composée avec ces différents aliments, en lui ajoutant une sauce faite maison avec un yaourt à 0% et du jus de citron, à laquelle vous pouvez éventuellement ajouter un peu de basilic pour une petite saveur agréable.\nVous pouvez également manger ses aliments séparément, selon votre goût.\nLorsque les aliments sont notés « à volonté », vous pouvez en manger autant que vous le souhaitez, jusqu’à ce que vous n’éprouviez plus de sensation de faim.",
      "Pour le dîner, c’est jambon cuit à volonté et salade verte à volonté, à choisir parmi les nombreuses sortes de salades présentées dans les magasins.\nIl ne faut pas oublier que le sel est à bannir.\nLa sauce doit être faite à la maison, et non pas achetée toute prête, car ce genre de sauce contient des matières grasses et du sel, ce qui est totalement déconseillé dans ce régime.\nVotre sauce doit être préparée avec un yaourt à 0% de matière grasse et du jus de citron. Le citron est souvent utilisé dans les régimes comme le régime Thonon car il a un pouvoir curatif, détoxifiant et amaigrissants. Il agit efficacement contre la perte de poids.\nIl est à rappeler également que le jambon cuit est une très bonne source de protéines, indispensable pour garder votre masse musculaire. Le jambon cuit est peu calorique, ce qui en fait un aliment apprécié dans le régime Thonon.\nA noter également que le jambon cuit ne contient que très peu de matières grasses, environ 3 grammes pour 100 grammes de jambon cuit.",
    );
  }
}
