import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour8Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 8",
      "Vous avez le droit de boire du café vert sans sucre (sauf sucre de synthèse), ou bien du thé vert sans sucre également (sauf sucre de synthèse).\nVous pouvez boire l’une ou l’autre de ces boissons à volonté.\nLe café vert est en fait du café non torréfié, du fruit mût du caféier cueilli dès qu’il est mûr. Le café vert garde ses vertus naturelles qui sont détruites lors de la torréfaction. Le café vert est une boisson qui fait perdre du poids par ses principes actifs et qui protégerait également des risques de diabètes de type 2.\nLe thé vert a quasiment les mêmes fonctions que le café vert, agit sur la perte de poids, et aurait une capacité à faire baisser la tension, et prévenir les maladies cardiovasculaires.",
      "Pour le déjeuner, vous avez le droit de manger deux œufs durs et des épinards à volonté, toujours sans sel.\nLes œufs doivent être de calibre « moyen ».\nLes œufs durs ont la faculté d’être un aliment coupe faim. Ils constituent également un excellent substitut à la viande. L’œuf est très riche en protéines, c’est pour cela qu’il est recommandé lors de régimes amaigrissants. Il contient des acides aminés, de la vitamine A, D, E, B12. Il apporte également à l’organisme du zinc, du phosphore, du fer, du potassium et du magnésium. Sa valeur énergétique est faible, pour un gros œuf, elle est d’environ 75 calories.\nVous pouvez choisir des épinards frais ou surgelés, selon votre préférence. Les épinards sont à déguster à volonté. Pour leur donner un peu de goût, pensez aux aromates, si vous avez du mal à les manger nature. Il faut savoir que l’épinard est le légume le plus riche en fibres. Il stimule, de ce fait, le transit intestinal et il est très digeste. L’épinard est un véritable légume minceur. Il contient de nombreux minéraux dont le calcium et le potassium.",
      "Concernant le dîner du huitième jour, vous avez le droit de manger un grand steak grillé, ou de le remplacer par trois petits steaks hachés.\nBien entendu, aucune matière grasse, pas de sel et pour la cuisson, les faire revenir dans une poêle ou les passer au grille viande. Vous pouvez les aromatiser de quelques herbes, pour leur donner une saveur nouvelle.\nIl est important de conserver votre masse musculaire et de consommer des protéines pour continuer à perdre du poids. Vous devez donc manger votre grand steak ou si vous préférez trois petits steaks hachés et ne pas en laisser. Le corps humain a besoin de protéines, elles lui sont indispensables. La viande bovine est un excellent apport en protéines. Vous ne devez donc pas faire l’impasse sur le steak du dîner.\nEn accompagnement vous avez le droit de manger de la salade à volonté. Vous pouvez choisir entre différentes sortes de salades comme la roquette, la frisée, la laitue ou encore la scarole. Il n’y a pas de restriction pour la salade. Vous pouvez agrémenter votre salade avec la sauce faite maison composée d’un yaourt à 0% de matière grasse et de citron.\nEn plus de la salade, vous devez consommer du céleri. Vous pouvez le râper et le mélanger à votre salade ou le déguster à part. La consommation de céleri est à volonté. Il ne faut pas acheter des barquettes toutes prêtes car elles sont assaisonnées généralement avec de l’huile et elle comportent un ajout de sel. Vous devez consommez du céleri que vous aurez préparé vous-même, et l’accompagner avec la sauce maison, si vous le désirez.",
    );
  }
}
