import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour13Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 13",
      "Vous avez le droit de boire du café vert ou du thé vert sans sucre. Le sucre de synthèse est autorisé.\nLe café vert est du café qui n’a pas été torréfié et qui a gardé toutes ses propriétés naturelles. De ce fait c’est une excellente boisson qui est conseillée dans le régime Thonon car elle a des vertus amaigrissantes. Le café vert contiendrait également des principes actifs qui protégeraient du diabète de type 2. Ce diabète est présent chez les personnes qui ont un poids très important et chez les personnes obèses.\nLe thé vert est également recommandé dans le régime Thonon, car il est également reconnu dans le processus de la perte de poids, et il posséderait également une capacité à faire baisser la tension.\nVous pouvez manger un petit pain. De préférence, il est conseillé de manger un petit pain complet plutôt que du pain blanc. Le pain complet contient plus de fibres et de nutriments que le pain blanc. Le pain complet est plus long à digérer. De ce fait, il vous évitera le petit creux du milieu de matinée, et vous pourrez attendre le déjeuner sans trop avoir faim. Le pain complet assure également un bon transit intestinal.",
      "Pour votre déjeuner du treizième jour, vous avez le droit de manger du poulet grillé à volonté. Il n’y a aucune limite, vous pouvez en manger jusqu’à en être rassasié, car c’est le seul aliment autorisé pour ce repas.\nBien entendu, il est interdit d’ajouter de l’huile ou autre matière grasse, et le sel est à bannit.\nVous pouvez le faire revenir dans une poêle sans matière grasse, ou le mettre dans un plat au four, avec quelques herbes aromatiques pour parfumer vos filets de poulet.\nLe poulet grillé ne veut pas dire poulet rôti. Le poulet rôti n’est pas autorisé dans le régime Thonon, car il comporte des matières grasses et en plus il est salé, ce qui déstabiliserait le processus du régime. Ce sont donc des filets de poulet nature qu’il faut acheter.\nPourquoi du poulet à volonté ?\nLe poulet est une viande blanche et c’est une viande maigre. Certaines parties du poulet sont plus utilisées pour suivre un régime amaigrissant, ce sont les filets. Les blancs de poulet constituent l’élément de base pour entreprendre un régime. En effet, c’est une source très riche en protéines et pauvre en graisse. Les filets de poulet sont un atout minceur et sont indispensables dans un régime comme le régime Thonon, car ils préservent une alimentation équilibrée.\nIls sont riches en acides aminés et en oligo-éléments : vitamines B et PP, du fer, du phosphore et du zinc. Vous trouverez dans cet aliment une réelle source de tonus.\nPour 100 grammes de filets de poulet, il faut compter environ une centaine de calories. De plus, les filets de poulet sont peu onéreux et faciles à cuisiner. Ils sont des alliés pour votre ligne, comme pour votre forme !",
      "Pour le dîner du treizième jour, vous avez le droit de manger deux œufs durs et une salade de carottes crues avec du jus de citron.\nLe sel est à bannir.\nLes œufs durs sont une source de protéines immense et ont la faculté d’être un aliment coupe-faim.\nIls sont très intéressants et très recherchés lors d’un régime comme le régime Thonon. Lorsque vous mangez deux œufs durs de calibre moyen, votre estomac est rassasié et vous n’avez plus faim. L’œuf dur est un excellent substitut à la viande.\nLes œufs contiennent de nombreuses vitamines, comme A, E, B12, D, des acides aminés, ainsi que des oligo-éléments comme le zinc, le phosphore, le fer, et le magnésium. Les œufs durs ont un apport calorique très faible, ce qui en fait un excellent aliment pour une perte de poids importante.\nNéanmoins, il ne faut pas intervertir les repas, et encore moins les menus. Vous ne devez pas changer les œufs pour de la viande blanche, ni le contraire.\nLe principe du régime Thonon est une réaction chimique entre les aliments que vous mangez. Donc, si vous changez quoi que ce soit, vous déstabiliser le régime et il ne sera pas autant satisfaisant que vous l’auriez souhaité.\nPour accompagner vos œufs durs, vous pouvez vous préparer une salade de carottes crues agrémentées d’un filet de jus de citron, ou si vous préférez manger chaud, des carottes cuites sans ajout de sel, et natures.",
    );
  }
}
