import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour11Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 11",
      "Pour le petit-déjeuner du onzième jour, vous avez le droit de boire du café vert ou du thé vert sans sucre. Le sucre de synthèse est autorisé, si vous ne pouvez pas supporter le café ou le thé nature.\nPour compléter votre petit-déjeuner, vous avez le droit à un petit pain. Il est préférable de prendre un petit pain complet. Le pain complet est meilleur pour la santé que le pain blanc. Il contient des fibres et des nutriments qui sont conseillés lors de régimes. De plus, le pain complet est plus long à digérer que le pain blanc, ce qui évitera le petit creux du matin, et vous pourrez tenir jusqu’au repas de midi sans trop de soucis.",
      "Pour votre déjeuner, vous allez manger un œuf dur, accompagné d’une salade de carottes crues ou de carottes cuites, selon votre convenance, ainsi qu’un morceau de gruyère.\nUn petit rappel concernant les aliments qui sont proposés dans le régime Thonon.\nL’œuf dur à la particularité de bien caler, c’est pour cela que c’est un formidable coupe-faim. De plus, il fait partie de ces aliments très riches en protéines. Il faut savoir qu’un œuf peut très bien remplacé la viande lors d’un repas. Il est également très chargé en vitamines et en nutriments qui sont essentiels pour l’organisme. L’œuf est également très peu calorique, ce qui en fait un excellent aliment à prendre en considération lors de régimes amaigrissants comme le régime Thonon.\nVous pouvez très bien accompagner cet œuf dur avec une petite salade de carottes crues, ou si vous préférer de carottes cuites, que vous aurez agrémenté de quelques herbes aromatique pour donner plus de goût.\nBien entendu, pour chacun de ses aliments, le sel est à bannir.\nCe onzième jour, vous avez le droit à une portion de gruyère. Une portion de gruyère couvre 1/3 des besoins journaliers en calcium. Le gruyère est un bon rapport calcium/calories. Il n’est pas totalement interdit dans les régimes, car il ne contient pas trop de calories. Si vous n’aimez pas le gruyère, vous pouvez aisément le remplacer par du Beaufort (120 calories pour 30 grammes), du Comté (125 calories pour 30 grammes) ou encore l’Emmental (115 calories pour 30 grammes).\nPour vous donner une petite idée, 30 grammes de fromage à pâte dure correspondent à environ 1/8ème de camembert.",
      "Pour votre le dîner du onzième jour, vous avez le droit de manger des fruits à volonté (vous référer à la liste des « fruits à volonté », que choisir ?\nVous compèterez votre dîner avec un yaourt entier sans sucre.\nConcernant les fruits, vous pouvez manger jusqu’à deux bananes maximum, et compléter par des fruits plus légers comme le kiwi, la poire, oranges et mandarines, prunes, pastèque, melon. Il vous est possible de grignoter quelques fruits secs, sans trop en abuser.\nSi vous avez encore un petit creux, terminer le repas en croquant une pomme. Ce fruit n’est quasiment pas calorique, et de plus c’est un excellent coupe-faim naturel. Il ne faut pas s’en priver.",
    );
  }
}
