import 'package:flutter/material.dart';
import 'package:regime_thonon/widget/JourBasePage.dart';

class Jour9Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return JourPage("Jour 9",
      "Pour le neuvième jour, vous avez le droit de boire du café vert ou du thé vert, selon votre envie et votre préférence, sans ajout de sucre (éventuellement du sucre de synthèse). Vous avez la possibilité d’ajouter un peu de lait écrémé ou de soja, comme indiqué dans le tableau des aliments autorisés. Vous ne devez pas dépasser les 100 ml de lait.",
      "Le déjeuner du neuvième jour est un peu plus consistant. C’est à vous de bien faire attention aux proportions, pour que vous puissiez manger de tout.\nVous avez le droit de manger un grand steak sans sel et sans matière grasse. Il faut le faire simplement griller, pour cela vous pouvez le faire cuire à la poêle, ou encore mieux au grille viande. Vous pouvez ajouter quelques herbes aromatiques.\nN’oubliez pas, il est important que vous mangiez votre steak, comme indiqué dans le menu. C’est une source indispensable de protéines, et votre corps en a besoin.\nAvec votre steak, vous avez le droit de manger de la salade verte et des tomates. Différentes sortes de salade vous sont proposées et concernant les tomates, deux à trois belles tomates devraient vous convenir.\nVous pouvez manger ces légumes séparément, ou bien vous concocter une jolie salade de couleur en mélangeant les deux légumes. Le sel et les matières grasses sont toujours à bannir. Si vous avez du mal à les manger nature, vous pouvez éventuellement les accompagner de la sauce maison faite avec un yaourt à 0% de matière grasse et du jus de citron.\nAujourd’hui, vous avez le droit en plus à un dessert : des fruits à volonté.\nVous pouvez choisir vos fruits dans la liste « les fruits à volonté, comment choisir ? ».\nConcernant les fruits à volonté, et après un repas un peu plus copieux, il est préférable de choisir des fruits qui ont un indice calorique faible. Il serait préférable de se diriger vers les fruits comme le kiwi (47 Kcalories pour 100 grammes) ou encore la poire (61 kcalories pour 100 grammes). Les fraises, l’ananas, la pastèque, les cerises (selon la période de l’année) sont également des fruits peu caloriques et à forte teneur en vitamine C. A la fin de votre repas, vous pouvez très bien terminer celui-ci par une pomme (50 kcalories pour 100 grammes). C’est le fruit idéal car sont aux de calories est très bas et elle agit comme un coupe-faim.",
      "Pour le dîner, vous avez le droit de manger des tranches de jambon cuit à volonté. Vous pouvez en manger jusqu’à être totalement rassasiée.\nPour le jambon cuit, vous pouvez en consommer autant que vous le désirez, même s’il est considéré qu’il serait préférable d’en consommer, selon les proportions en protéines recommandées par l’OMC, c’est-à-dire aux alentours de 0.8 grammes par jour par kilo selon votre poids.\nComment se fait-il que vous puissiez manger du jambon cuit à volonté ?\nTout simplement parce que le jambon cuit ne contient que très peu de matières grasses, environ 3 grammes pour 100 grammes de jambon cuit. De plus, le jambon cuit est un aliment hyperprotéiné et qui est recommandé dans le régime Thonon. Ce qui en fait un aliment parfait. Il est également prouvé qu’une tranche de jambon couvre en moyenne environ 17 % des apports journaliers en protéines pour les femmes et 13 % pour les hommes. Un petit rappel : les apports journaliers en protéines sont en principe de 0,8 grammes que vous devez multiplier par votre poids en kilos. Il est très pauvre en calories : une tranche de jambon cuit de 50 grammes environ ne contient que 60 calories. Ce qui fait du jambon cuit, un aliment particulièrement apprécié et efficace dans le régime Thonon, par son faible taux calorique, et son apport en protéines important.",
    );
  }
}
